package functions

data private class Emp(var n:String,var id:Int)
fun main() {
    var obj1=Emp("ksjdn",5)  // it is the normal way of creating object
    println("  ${obj1.n} and ${obj1.id}")

    //now , using apply function for creating the object
    var apply_obj=obj1.apply {
        id=5
        n="ksd"
    }

    println("object generated by apply function :: ${apply_obj.n}  ====   ${apply_obj.id} ")

}